### ISSUE TITLE
Usage of rand_perm_cam.mat file

### ISSUE THREAD

**Issue by chaitrasj** [InnovArul/SYSU_MM01_pythoneval#1]
Hi, Thanks a lot for open souring this implementation!
I have a doubt regarding the contents of rand_perm_cam.mat file. I understand it has some fixed split of gallery images. But can you please elaborate why is it needed for the evaluation of map and cmc scores because in some other others for calculating rb ir cross modal person reid accuracy, it is not getting used.
Thanks

**Comment by InnovArul** [comment]
As I remember, `rand_perm_cam.mat` contains fixed 10 splits (defined by dataset authors) to be evaluated for the model and average performance is to be reported.
In my understanding, All the state-of-the-art models are supposed to evaluate the defined splits while reporting results on SYSU-MM01 dataset.

`rand_perm_cam.mat` is taken as it is, from dataset author's codebase: https://github.com/wuancong/SYSU-MM01/tree/master/evaluation/data_split

**Comment by chaitrasj** [comment]
Okay makes sense.
Thank you
